"""Tests for the documenteer.services.technotecff module."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from documenteer.services.technotecff import CffStatus, TechnoteCffService

FULL_TOML = """
[technote]
id = "SQR-000"
series_id = "SQR"
title = "The LSST DM Technical Note Publishing Platform"
canonical_url = "https://sqr-000.lsst.io/"
github_url = "https://github.com/lsst-sqre/sqr-000"
doi = "10.71929/rubin/2570308"
date_updated = 2026-08-24

[technote.organization]
name = "Vera C. Rubin Observatory"
ror = "https://ror.org/048g3cy84"

[[technote.authors]]
name = {given = "Jonathan", family = "Sick"}
internal_id = "sickj"
orcid = "https://orcid.org/0000-0003-3001-676X"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
"""


def test_render_preferred_citation(tmp_path: Path) -> None:
    """A technote renders as a CFF 1.2.0 file whose preferred-citation is a
    report carrying the technote's DOI, number, publisher, and URL.
    """
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(FULL_TOML)

    service = TechnoteCffService.from_technote_toml(toml_path)
    text = service.render()

    assert text.startswith(
        "# Generated by documenteer technote sync-cff from technote.toml "
        "— do not edit\n"
    )

    document = yaml.safe_load(text)
    assert document["cff-version"] == "1.2.0"
    assert document["type"] == "software"
    assert document["title"] == (
        "The LSST DM Technical Note Publishing Platform"
    )

    reference = document["preferred-citation"]
    assert reference["type"] == "report"
    assert reference["title"] == (
        "The LSST DM Technical Note Publishing Platform"
    )
    assert reference["doi"] == "10.71929/rubin/2570308"
    assert reference["number"] == "SQR-000"
    assert reference["institution"] == {"name": "Vera C. Rubin Observatory"}
    assert reference["url"] == "https://sqr-000.lsst.io/"
    assert str(reference["date-released"]) == "2026-08-24"


def test_authors_round_trip(tmp_path: Path) -> None:
    """An author's ORCID and affiliation reach both author lists."""
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(FULL_TOML)

    document = yaml.safe_load(
        TechnoteCffService.from_technote_toml(toml_path).render()
    )

    author = {
        "family-names": "Sick",
        "given-names": "Jonathan",
        "orcid": "https://orcid.org/0000-0003-3001-676X",
        "affiliation": "Rubin Observatory Project Office",
    }
    assert document["authors"] == [author]
    assert document["preferred-citation"]["authors"] == [author]


def test_bare_orcid_becomes_a_url(tmp_path: Path) -> None:
    """CFF requires an ORCID as an orcid.org URL, whatever technote.toml
    spells it as.
    """
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(
        FULL_TOML.replace(
            'orcid = "https://orcid.org/0000-0003-3001-676X"',
            'orcid = "0000-0003-3001-676X"',
        )
    )

    document = yaml.safe_load(
        TechnoteCffService.from_technote_toml(toml_path).render()
    )

    assert (
        document["authors"][0]["orcid"]
        == "https://orcid.org/0000-0003-3001-676X"
    )


def test_technote_without_doi(tmp_path: Path) -> None:
    """A technote with no DOI still generates a file; the DOI is omitted."""
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(
        FULL_TOML.replace('doi = "10.71929/rubin/2570308"\n', "")
    )

    document = yaml.safe_load(
        TechnoteCffService.from_technote_toml(toml_path).render()
    )

    assert "doi" not in document["preferred-citation"]
    assert document["preferred-citation"]["url"] == "https://sqr-000.lsst.io/"


def test_untitled_technote_falls_back_to_its_id(tmp_path: Path) -> None:
    """A technote that declares no title is titled by its ID, with a
    warning for the caller to report.
    """
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(
        FULL_TOML.replace(
            'title = "The LSST DM Technical Note Publishing Platform"\n', ""
        )
    )

    service = TechnoteCffService.from_technote_toml(toml_path)

    assert yaml.safe_load(service.render())["title"] == "SQR-000"
    assert len(service.warnings) == 1
    assert "no title" in service.warnings[0]


def test_status_and_sync(tmp_path: Path) -> None:
    """A CITATION.cff is absent, then current, and re-syncing leaves it
    byte-for-byte untouched.
    """
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(FULL_TOML)
    cff_path = tmp_path / "CITATION.cff"
    service = TechnoteCffService.from_technote_toml(toml_path)

    assert service.status(cff_path) is CffStatus.absent
    assert service.sync(cff_path) is CffStatus.absent
    assert service.status(cff_path) is CffStatus.current

    mtime = cff_path.stat().st_mtime_ns
    assert service.sync(cff_path) is CffStatus.current
    assert cff_path.stat().st_mtime_ns == mtime


def test_status_stale(tmp_path: Path) -> None:
    """A CITATION.cff that does not match technote.toml is stale."""
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(FULL_TOML)
    cff_path = tmp_path / "CITATION.cff"
    cff_path.write_text("cff-version: 1.2.0\n")

    service = TechnoteCffService.from_technote_toml(toml_path)

    assert service.status(cff_path) is CffStatus.stale
    assert service.sync(cff_path) is CffStatus.stale
    assert service.status(cff_path) is CffStatus.current


def test_malformed_doi_is_rejected(tmp_path: Path) -> None:
    """A DOI that is not a DOI is reported where the metadata is read."""
    toml_path = tmp_path / "technote.toml"
    toml_path.write_text(
        FULL_TOML.replace(
            'doi = "10.71929/rubin/2570308"', 'doi = "not-a-doi"'
        )
    )

    with pytest.raises(ValueError, match="Not a DOI"):
        TechnoteCffService.from_technote_toml(toml_path)
