version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    reviewers:
      - "jonathansick"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    reviewers:
      - "jonathansick"
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      npm:
        patterns:
          - "*"
