"""Parses a documenteer.toml configuration file to support documenteer's
configuration preset modules.
"""

from __future__ import annotations

import datetime
import sys
import tomllib
from collections.abc import MutableMapping
from dataclasses import dataclass, field
from email.message import Message
from functools import cached_property
from importlib.metadata import PackageNotFoundError, metadata
from importlib.metadata import version as get_version
from pathlib import Path
from typing import Any, Self, cast
from urllib.parse import urlparse

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    FilePath,
    HttpUrl,
    ValidationError,
    field_validator,
    model_validator,
)
from sphinx.errors import ConfigError

from ..citations import (
    Citation,
    CitationAuthor,
    CitationType,
    GuideCitation,
    OrganizationAuthor,
    PersonAuthor,
    compose_landing_page_jsonld,
    normalize_doi,
)
from ..storage.citationcff import CitationCffError, read_citation_cff
from ..storage.intersphinxcacheclient import (
    DEFAULT_BASE_URL as INTERSPHINX_CACHE_DEFAULT_BASE_URL,
)
from ..storage.linkcheckclient import DEFAULT_BASE_URL as OOK_DEFAULT_BASE_URL
from ._utils import normalize_origin_base_url

__all__ = [
    "CitationAuthorModel",
    "CitationModel",
    "ConfigRoot",
    "DocumenteerConfig",
    "IntersphinxCacheModel",
    "IntersphinxModel",
    "LinkCheckModel",
    "OpenApiDocsModel",
    "OpenApiGeneratorModel",
    "ProjectModel",
    "PythonPackageModel",
    "SphinxModel",
    "ThemeModel",
]


class OpenApiGeneratorModel(BaseModel):
    """Specification for the OpenAPI generator function used by the
    ``documenteer.ext.openapi`` Sphinx extension.
    """

    function: str = Field(
        description=(
            "The Python function that generates the OpenAPI spec file. "
            "It must have the form ``module:func``. The function must return "
            "a JSON-serialized string."
        )
    )

    positional_args: list[Any] = Field(
        default_factory=list,
        description=(
            "Positional arguments to pass to the generator function."
        ),
    )

    keyword_args: dict[str, Any] = Field(
        default_factory=dict,
        description=("Keyword arguments to pass to the generator function."),
    )


class OpenApiDocsModel(BaseModel):
    """Model for OpenAPI documentation configurations in documenteer.toml."""

    generator: OpenApiGeneratorModel | None = Field(
        None,
        description=(
            "The function that generates the OpenAPI spec file from the"
            "application source code. If not specified, the OpenAPI spec file "
            "assumed to be generated by an external process and provided at "
            "the path specified by ``openapi_path``."
        ),
    )

    openapi_path: str = Field(
        "_static/openapi.json",
        description=(
            "This is the path, relative to the Sphinx conf.py file, where the "
            "OpenAPI spec file is written. Default is "
            "``_static/openapi.json``."
        ),
    )

    doc_path: str = Field(
        "api",
    )


class PythonPackageModel(BaseModel):
    """Model for a Python package (i.e. built with pyproject.toml-compatible
    build system.
    """

    package: str = Field(description="Package name")

    documentation_url_key: str = Field(
        "Homepage",
        description=(
            "Key for the documentation URL in the pyproject.toml "
            "[project.urls] table. The corresponding URL is used for "
            "the Sphinx html_baseurl configuration, which in turns sets the "
            "canonical URL link relation on the web pages."
        ),
    )

    github_url_key: str = Field(
        "Source",
        description=(
            "Key for the documentation URL in the pyproject.toml "
            "[project.urls] table. The corresponding URL is used for "
            "as an alternative to setting [project.github_url]."
        ),
    )

    @field_validator("package")
    @classmethod
    def validate_package(cls, v: str) -> str:
        """Ensure the package is importable."""
        try:
            get_version(v)
        except PackageNotFoundError as e:
            raise ValueError(f"The package {v!r} is not importable.") from e
        return v


class CitationAuthorModel(BaseModel):
    """Model for an author of a ``[[project.citations]]`` entry.

    An author is either a person, named with ``family_name`` (and usually
    ``given_name``), or an organization, named with ``name``. The split
    matters to a rendered citation: a person's name is set family-name-first
    and may be abbreviated by a BibTeX style, where an organization's is
    protected from both.
    """

    name: str | None = Field(
        None,
        description=(
            "The organization's name, for an author that is an institution "
            "rather than a person."
        ),
    )

    ror: str | None = Field(
        None,
        description=(
            "The organization's ROR (ror.org) identifier. Only meaningful "
            "alongside ``name``."
        ),
    )

    family_name: str | None = Field(
        None,
        description=(
            "The person's family name (last name in western culture)."
        ),
    )

    given_name: str | None = Field(
        None,
        description=(
            "The person's given name (first name in western culture)."
        ),
    )

    orcid: str | None = Field(
        None,
        description=(
            "The person's ORCID, as a URL or a bare identifier. Only "
            "meaningful alongside ``family_name``."
        ),
    )

    affiliation: str | None = Field(
        None,
        description=(
            "The person's affiliation, as a single display name. Only "
            "meaningful alongside ``family_name``."
        ),
    )

    @model_validator(mode="after")
    def validate_name(self) -> Self:
        """Require exactly one of the organization and person spellings."""
        if self.name is not None and self.family_name is not None:
            raise ValueError(
                "A citation author sets both name and family_name. Use name "
                "for an organization and family_name for a person, not both."
            )
        if self.name is None and self.family_name is None:
            raise ValueError(
                "A citation author has no name. Give it either name (for an "
                "organization) or family_name (for a person)."
            )
        return self

    def to_citation_author(self) -> CitationAuthor:
        """Express the author as a `documenteer.citations.CitationAuthor`."""
        if self.name is not None:
            return OrganizationAuthor(name=self.name, ror=self.ror)
        # validate_name guarantees a family name when there is no org name.
        return PersonAuthor(
            family_name=cast("str", self.family_name),
            given_name=self.given_name,
            orcid=self.orcid,
            affiliation=self.affiliation,
        )


class CitationModel(BaseModel):
    """Model for an entry in the ``[[project.citations]]`` array of
    documenteer.toml.

    An entry carries both the work's bibliographic fields and the
    presentation fields that say how the site displays it. The bibliographic
    fields can instead come from a CITATION.cff file, named by ``cff``, in
    which case a field set here overrides the file's value; the presentation
    fields are only ever set here.
    """

    model_config = ConfigDict(populate_by_name=True)

    doi: str | None = Field(
        None,
        description=(
            "The work's DOI, written bare (``10.NNNN/suffix``), as a "
            "https://doi.org/ URL, or with a ``doi:`` prefix. Required "
            "unless a ``cff`` file supplies one."
        ),
    )

    label: str | None = Field(
        None,
        description=(
            "A short label distinguishing this citation from the site's "
            'others, such as "Dataset" or "Paper".'
        ),
    )

    type: CitationType | None = Field(
        None,
        description=(
            "The kind of work being cited, which decides the schema.org "
            "type the site publishes it under. A cff file supplies one when "
            "this is unset."
        ),
    )

    is_self: bool = Field(
        False,
        alias="self",
        description=(
            "Whether this is the DOI whose landing page this site is. At "
            "most one entry can set it."
        ),
    )

    in_footer: bool | None = Field(
        None,
        description=(
            "Whether this citation appears in the site footer. Defaults to "
            "true for the ``self`` entry and false for every other."
        ),
    )

    note: str | None = Field(
        None,
        description=(
            "Free text about when to use this citation, displayed alongside "
            "it."
        ),
    )

    title: str | None = Field(None, description="The title of the cited work.")

    authors: list[CitationAuthorModel] = Field(
        default_factory=list,
        description=(
            "The work's authors, in the order they should be credited. "
            "Setting any author replaces the whole author list a ``cff`` "
            "file supplies."
        ),
    )

    publisher: str | None = Field(
        None, description="The organization that published the work."
    )

    date: datetime.date | None = Field(
        None,
        description=(
            "The work's publication date. Only its year appears in a "
            "rendered citation."
        ),
    )

    cff: str | None = Field(
        None,
        description=(
            "Path to a CITATION.cff file supplying the bibliographic "
            "fields, relative to documenteer.toml (typically "
            "``../CITATION.cff``)."
        ),
    )

    @field_validator("doi")
    @classmethod
    def validate_doi(cls, v: str | None) -> str | None:
        """Normalize the DOI to its bare form, rejecting a non-DOI."""
        if v is None:
            return None
        return normalize_doi(v)

    @property
    def shows_in_footer(self) -> bool:
        """Whether the citation appears in the site footer, resolving the
        default from whether it is the self citation.
        """
        if self.in_footer is None:
            return self.is_self
        return self.in_footer


class ProjectModel(BaseModel):
    """Model for the project table in the documenteer.toml file."""

    title: str = Field(
        description=(
            "Name of the project, used as titles throughout the documentation "
            "site."
        )
    )

    base_url: HttpUrl | None = Field(
        None, description="Canonical URL of the site's root page."
    )

    copyright: str = Field(
        "",
        description="Copyright statement, without a 'copyright' prefix word.",
    )

    github_url: HttpUrl | None = Field(
        None, description="The URL of the project's GitHub repository."
    )

    github_default_branch: str = Field(
        "main",
        description="The project's default development branch on GitHub.",
    )

    version: str | None = Field(None, description="Version string.")

    python: PythonPackageModel | None = Field(None)

    openapi: OpenApiDocsModel | None = Field(None)

    citations: list[CitationModel] = Field(
        default_factory=list,
        description=(
            "Citations the site displays, in the order they appear in the "
            "footer."
        ),
    )

    @field_validator("citations")
    @classmethod
    def validate_one_self_citation(
        cls, v: list[CitationModel]
    ) -> list[CitationModel]:
        """Allow at most one citation to claim the site as its landing
        page.
        """
        self_count = sum(1 for citation in v if citation.is_self)
        if self_count > 1:
            raise ValueError(
                f"{self_count} [[project.citations]] entries set self = "
                "true, but a site is the landing page of at most one DOI. "
                "Set self = true on one entry only."
            )
        return v


class IntersphinxCacheModel(BaseModel):
    """Model for the Ook intersphinx inventory cache configuration in
    documenteer.toml.
    """

    use_service: bool = Field(
        True,
        description=(
            "Prefetch intersphinx object inventories from Ook's inventory "
            "cache service so builds do not depend on third-party site "
            "availability."
        ),
    )

    service_url: HttpUrl = Field(
        HttpUrl(INTERSPHINX_CACHE_DEFAULT_BASE_URL),
        description=(
            "Base URL of the Ook API that hosts the intersphinx inventory "
            "cache service."
        ),
    )

    disk_cache_ttl: int = Field(
        600,
        ge=0,
        description=(
            "Seconds an on-disk cached inventory stays fresh before the "
            "client revalidates it with Ook. Within this window, successive "
            "builds reuse the local file without contacting Ook at all. "
            "Set to 0 to disable the fast path so every build revalidates "
            "with Ook."
        ),
    )

    warn_on_permanent_redirect: bool = Field(
        False,
        description=(
            "Report an intersphinx inventory URL that has permanently moved "
            "as a Sphinx warning rather than an informational message, so a "
            "warnings-as-errors (-W) build fails until the URL is updated. "
            "The warning carries the subtype "
            "documenteer.intersphinx_permanent_redirect, so it can be "
            "silenced per-project with suppress_warnings. Default is false "
            "because the move originates upstream, outside the author's "
            "control."
        ),
    )


class IntersphinxModel(BaseModel):
    """Model for Intersphinx configurations in documenteer.toml."""

    projects: dict[str, HttpUrl] = Field(
        description="Mapping of projects and their URLs.", default_factory=dict
    )

    cache: IntersphinxCacheModel = Field(default_factory=IntersphinxCacheModel)


class LinkCheckModel(BaseModel):
    """Model for linkcheck builder configurations in documenteer.toml."""

    ignore: list[str] = Field(
        description="Regular expressions of URLs to skip checking links",
        default_factory=list,
    )

    use_service: bool = Field(
        True,
        description=(
            "Check links with Ook's link-check service instead of Sphinx's "
            "built-in linkcheck builder."
        ),
    )

    service_url: HttpUrl = Field(
        HttpUrl(OOK_DEFAULT_BASE_URL),
        description=(
            "Base URL of the Ook API that hosts the link-check service."
        ),
    )

    poll_budget: int = Field(
        300,
        description=(
            "Maximum time (seconds) to wait for link-check results from "
            "the service."
        ),
    )

    strict: bool = Field(
        False,
        description=(
            "Fail the build when the link-check service is unavailable "
            "instead of degrading to a warning."
        ),
    )

    recheck_unverified: bool = Field(
        True,
        description=(
            "Recheck URLs the link-check service could not verify from its "
            "own vantage point — blocked by bot protection, or broken with "
            "no HTTP status code because it got no response at all — from "
            "this build's own vantage point, merging what the build "
            "observes into the report."
        ),
    )

    origin_base_url: HttpUrl | None = Field(
        None,
        description=(
            "Origin base URL override for the link-check service: the "
            "full base URL of the website the links are submitted for "
            "(e.g. https://documenteer.lsst.io). By default the origin "
            "is project.base_url. The URL is normalized by lowercasing "
            "the host and stripping any trailing slash."
        ),
    )


class ThemeModel(BaseModel):
    """Model for theme configurations in documenteer.toml."""

    show_github_edit_link: bool = Field(
        True, description="Show a link to edit on GitHub if True"
    )

    header_links_before_dropdown: int = Field(
        5,
        description=(
            "Number of links in the header nav before showing a 'More' "
            "dropdown."
        ),
    )

    show_last_updated: bool = Field(
        True,
        description=(
            "Show a 'Last updated' timestamp at the bottom of each page "
            "derived from Git commit dates if True"
        ),
    )


class SphinxModel(BaseModel):
    """Model for Sphinx configurations in documenteer.toml."""

    rst_epilog_file: FilePath | None = Field(
        None,
        description=(
            "Path to a reStructuredText file that is added to every source "
            "file. Use this file to define common links and substitutions."
        ),
    )

    extensions: list[str] = Field(
        description="Additional Sphinx extension.", default_factory=list
    )

    nitpicky: bool = Field(
        False, description="Escalate warnings to build errors."
    )

    nitpick_ignore: list[tuple[str, str]] = Field(
        description=(
            "Errors to ignore. First item is the type (like a role or "
            "directive) and the second is the target (like the argument to "
            "the role)."
        ),
        default_factory=list,
    )

    nitpick_ignore_regex: list[tuple[str, str]] = Field(
        description=(
            "Same as ``nitpick_ignore``, but both type and target are "
            "interpreted as regular expressions."
        ),
        default_factory=list,
    )

    disable_primary_sidebars: list[str] | None = Field(
        None,
        description=(
            "Pages that should not have a primary sidebar. Can be the page's "
            "path (without extension) or a glob of pages. By default the "
            "homepage and change logs do not have a primary sidebar."
        ),
    )

    python_api_dir: str | None = Field(
        None,
        description=(
            "Directory path where the Python API reference documentation "
            "is created."
        ),
    )

    exclude: list[str] = Field(
        description=(
            "List of paths to exclude from being considered as Sphinx content "
            "sources."
        ),
        default_factory=list,
    )

    theme: ThemeModel = Field(default_factory=ThemeModel)

    intersphinx: IntersphinxModel = Field(default_factory=IntersphinxModel)

    linkcheck: LinkCheckModel = Field(default_factory=LinkCheckModel)

    redirects: dict[str, str] = Field(
        description=(
            "Mapping of paths to redirect to other paths. These redirects "
            "are implemented with sphinx-rediraffe."
        ),
        default_factory=dict,
    )


class ConfigRoot(BaseModel):
    """The root model for a documenteer.toml configuration file."""

    project: ProjectModel

    sphinx: SphinxModel | None = None


@dataclass
class DocumenteerConfig:
    """Configuration from a documenteer.toml file."""

    conf: ConfigRoot

    root_dir: Path = field(default_factory=Path)
    """The directory the documenteer.toml file was loaded from.

    Paths in the configuration that are documented as relative to
    documenteer.toml — a citation's ``cff`` file, for instance — are resolved
    against this directory. Sphinx runs :file:`conf.py` with the
    configuration directory as the working directory, so the default (the
    working directory) is right for a build.
    """

    @classmethod
    def find_and_load(cls) -> DocumenteerConfig:
        path = Path("documenteer.toml")
        if not path.is_file():
            raise ConfigError("Cannot find the documenteer.toml file.")
        return cls.load(path.read_text(), root_dir=path.parent)

    @classmethod
    def load(
        cls, toml_content: str, *, root_dir: Path | None = None
    ) -> DocumenteerConfig:
        try:
            conf = ConfigRoot.model_validate(tomllib.loads(toml_content))
        except ValidationError as e:
            message = (
                f"Syntax or validation issue in documenteer.toml:\n\n{e!s}"
            )
            raise ConfigError(message) from e
        return cls(conf, root_dir=root_dir if root_dir is not None else Path())

    @property
    def project(self) -> str:
        """Project title."""
        return self.conf.project.title

    @property
    def base_url(self) -> str:
        """Base root URL for the site.

        The URL is obtained in this order:

        1. The ``base_url`` field of the ``[project]`` table in
           documenteer.toml.
        2. From importlib.metadata if ``[project.python]`` is set in
           documenteer.toml.
        3. Default is "".
        """
        if self.conf.project.base_url is not None:
            return str(self.conf.project.base_url)
        elif self.conf.project.python is not None:
            package_name = self.conf.project.python.package
            pyproject_meta = self._get_pyproject_metadata(package_name)
            url = self._get_pyproject_url(
                pyproject_meta, self.conf.project.python.documentation_url_key
            )
            if url is None:
                return ""
            return url
        return ""

    @property
    def copyright(self) -> str:
        """The copyright statement.

        Default is ``""`` if not set.
        """
        return self.conf.project.copyright

    @property
    def github_url(self) -> str | None:
        """The project's GitHub repository.

        The GitHub URL is obtained in this order:

        1. The project.github_url field in ``documenteer.toml``
        2. From importlib if the project.python table is set
        3. Default is None.
        """
        if self.conf.project.github_url is not None:
            # User explicitly set the github URL
            return str(self.conf.project.github_url)

        if self.conf.project.python is not None:
            # Get the URL from the package metadata
            package_name = self.conf.project.python.package
            pyproject_meta = self._get_pyproject_metadata(package_name)
            return self._get_pyproject_url(
                pyproject_meta, self.conf.project.python.github_url_key
            )

        return None

    @property
    def version(self) -> str | None:
        """The project's version.

        The version is obtained in this order:

        1. project.version field in ``documenteer.toml``
        2. From importlib if the project.python table is set
        3. Default is "Latest".
        """
        if self.conf.project.version is not None:
            return self.conf.project.version
        elif self.conf.project.python is not None:
            # Via pydantic validation we know this works
            return get_version(self.conf.project.python.package)
        else:
            return "Latest"

    @property
    def rst_epilog_path(self) -> Path | None:
        """Path to the user's reStructuredText epilog file, if set."""
        if self.conf.sphinx and self.conf.sphinx.rst_epilog_file is not None:
            return Path(self.conf.sphinx.rst_epilog_file)
        else:
            return None

    @property
    def rst_epilog(self) -> str:
        """Content of the user's reStructuredText epilog, or an empty string
        if not set.
        """
        if self.rst_epilog_path is None:
            return ""
        else:
            return self.rst_epilog_path.read_text()

    @property
    def redirects(self) -> dict[str, str]:
        """Redirects defined in the [sphinx.redirects] TOML configuration."""
        if self.conf.sphinx:
            return self.conf.sphinx.redirects
        else:
            return {}

    def _get_pyproject_metadata(self, package_name: str) -> Message:
        if sys.version_info >= (3, 10) or sys.version_info < (3, 8):
            pkg_metadata = cast("Message", metadata(package_name))
        else:
            pkg_metadata = metadata(package_name)
        return pkg_metadata

    def _get_pyproject_url(
        self, pkg_metadata: Message, label: str
    ) -> str | None:
        """Get a URL from a python package's metadata.

        Label corresponds to a field under [project.urls] in project.toml.
        """
        prefix = f"{label}, "
        for key, value in pkg_metadata.items():
            if key == "Project-URL":
                if value.startswith(prefix):
                    return value[len(prefix) :]
        return None

    def append_extensions(self, extensions: list[str]) -> None:
        """Append user-configured extensions to an existing list."""
        if self.conf.sphinx:
            for new_ext in self.conf.sphinx.extensions:
                if new_ext not in extensions:
                    extensions.append(new_ext)

    def extend_intersphinx_mapping(
        self, mapping: MutableMapping[str, tuple[str, str | None]]
    ) -> None:
        """Extend the ``intersphinx_mapping`` dictionary with configured
        projects.
        """
        if (
            self.conf.sphinx
            and self.conf.sphinx.intersphinx
            and self.conf.sphinx.intersphinx.projects
        ):
            for project, url in self.conf.sphinx.intersphinx.projects.items():
                mapping[project] = (str(url), None)

    @property
    def _intersphinx_cache(self) -> IntersphinxCacheModel:
        """The intersphinx cache configuration model, or its defaults if the
        [sphinx] table is not set.
        """
        if self.conf.sphinx:
            return self.conf.sphinx.intersphinx.cache
        return IntersphinxCacheModel()

    @property
    def intersphinx_cache_use_service(self) -> bool:
        """Whether to prefetch intersphinx inventories from Ook's inventory
        cache service.
        """
        return self._intersphinx_cache.use_service

    @property
    def intersphinx_cache_service_url(self) -> str:
        """Base URL of the Ook API that hosts the intersphinx inventory cache
        service (without a trailing slash).
        """
        return str(self._intersphinx_cache.service_url).rstrip("/")

    @property
    def intersphinx_cache_disk_cache_ttl(self) -> int:
        """Seconds an on-disk cached inventory stays fresh before the client
        revalidates it with Ook (0 disables the fast path).
        """
        return self._intersphinx_cache.disk_cache_ttl

    @property
    def intersphinx_cache_warn_on_permanent_redirect(self) -> bool:
        """Whether a permanently-moved intersphinx inventory URL is reported
        as a Sphinx warning (failing a ``-W`` build) rather than at info
        level.
        """
        return self._intersphinx_cache.warn_on_permanent_redirect

    def append_linkcheck_ignore(self, link_patterns: list[str]) -> None:
        """Append URL patterns for sphinx.linkcheck.ignore to existing
        patterns.
        """
        if self.conf.sphinx and self.conf.sphinx.linkcheck:
            link_patterns.extend(self.conf.sphinx.linkcheck.ignore)

    @property
    def _linkcheck(self) -> LinkCheckModel:
        """The linkcheck configuration model, or its defaults if the
        [sphinx] table is not set.
        """
        if self.conf.sphinx:
            return self.conf.sphinx.linkcheck
        return LinkCheckModel()

    @property
    def linkcheck_use_service(self) -> bool:
        """Whether to check links with Ook's link-check service instead of
        Sphinx's built-in linkcheck builder.
        """
        return self._linkcheck.use_service

    @property
    def linkcheck_service_url(self) -> str:
        """Base URL of the Ook API that hosts the link-check service
        (without a trailing slash).
        """
        return str(self._linkcheck.service_url).rstrip("/")

    @property
    def linkcheck_poll_budget(self) -> int:
        """Maximum time (seconds) to wait for link-check results from the
        service.
        """
        return self._linkcheck.poll_budget

    @property
    def linkcheck_strict(self) -> bool:
        """Whether link-check service degradation fails the build."""
        return self._linkcheck.strict

    @property
    def linkcheck_recheck_unverified(self) -> bool:
        """Whether URLs the link-check service could not verify from its
        own vantage point — bot-blocked, or broken with no response at all
        — are rechecked from the build's own vantage point, with the local
        observations merged into the report.
        """
        return self._linkcheck.recheck_unverified

    @property
    def linkcheck_origin_base_url(self) -> str | None:
        """The origin base URL for the link-check service.

        The origin is the ``[sphinx.linkcheck] origin_base_url`` override
        if set; otherwise it is the project's base URL. Either way it is
        normalized (lowercased host, trailing slash stripped) to match
        the service's origin normalization. `None` if neither is
        available.
        """
        if self._linkcheck.origin_base_url:
            return normalize_origin_base_url(
                str(self._linkcheck.origin_base_url)
            )
        base_url = self.base_url
        if not base_url:
            return None
        return normalize_origin_base_url(base_url)

    def append_nitpick_ignore(
        self, nitpick_ignore: list[tuple[str, str]]
    ) -> None:
        if self.conf.sphinx and self.conf.sphinx.nitpick_ignore:
            nitpick_ignore.extend(self.conf.sphinx.nitpick_ignore)

    def append_nitpick_ignore_regex(
        self, nitpick_ignore_regex: list[tuple[str, str]]
    ) -> None:
        if self.conf.sphinx and self.conf.sphinx.nitpick_ignore_regex:
            nitpick_ignore_regex.extend(self.conf.sphinx.nitpick_ignore_regex)

    @property
    def nitpicky(self) -> bool:
        if self.conf.sphinx:
            return self.conf.sphinx.nitpicky
        else:
            return False

    def extend_exclude_patterns(self, exclude_patterns: list[str]) -> None:
        """Extend Sphinx ``exclude_patterns`` with the "exclude" configuration
        from the sphinx TOML table.
        """
        if self.conf.sphinx and self.conf.sphinx.exclude:
            exclude_patterns.extend(self.conf.sphinx.exclude)

    def disable_primary_sidebars(
        self, html_sidebars: MutableMapping[str, list[str]]
    ) -> None:
        if self.conf.sphinx and self.conf.sphinx.disable_primary_sidebars:
            pages = self.conf.sphinx.disable_primary_sidebars
        else:
            pages = ["index"]  # default
        html_sidebars.update({name: [] for name in pages})

    @property
    def automodapi_toctreedirm(self) -> str:
        if self.conf.sphinx and self.conf.sphinx.python_api_dir is not None:
            return self.conf.sphinx.python_api_dir
        else:
            return "api"

    def set_edit_on_github(
        self,
        html_theme_options: MutableMapping[str, Any],
        html_context: MutableMapping[str, Any],
    ) -> None:
        """Configure the Edit on GitHub functionality, if possible.

        The in-repository path of the documentation source is *not* set here;
        it is resolved from the Sphinx source directory by the
        ``documenteer.ext.githubeditlink`` extension, which is the earliest
        point where the source directory is known.
        """
        if (
            self.conf.sphinx
            and self.conf.sphinx.theme.show_github_edit_link is False
        ):
            return

        if self.github_url is None:
            raise ConfigError(
                "sphinx.show_github_edit_link is True but the "
                "project.github_url is not set."
            )

        parsed_url = urlparse(self.github_url)
        path_parts = parsed_url.path.split("/")
        try:
            # first part is "/"
            github_owner = path_parts[1]
            github_repo = path_parts[2].split(".")[0]  # drop .git if present
        except IndexError as e:
            raise ConfigError(
                f"Could not parse GitHub repo URL: {self.github_url}"
            ) from e

        html_theme_options["use_edit_page_button"] = True
        html_context["github_user"] = github_owner
        html_context["github_repo"] = github_repo
        html_context["github_version"] = (
            self.conf.project.github_default_branch
        )

    @property
    def header_links_before_dropdown(self) -> int:
        """Number of links to show in the nav head before folding extra items
        into a More dropdown.
        """
        if self.conf.sphinx:
            return self.conf.sphinx.theme.header_links_before_dropdown
        else:
            return 5

    @property
    def show_last_updated(self) -> bool:
        """Whether to show a "Last updated" timestamp at the bottom of each
        page derived from Git commit dates.
        """
        if self.conf.sphinx:
            return self.conf.sphinx.theme.show_last_updated
        else:
            return True

    @cached_property
    def citations(self) -> list[GuideCitation]:
        """The citations declared in ``[[project.citations]]``, resolved and
        composed, in the order they are declared.

        Returns
        -------
        list
            A `~documenteer.citations.GuideCitation` per entry, each pairing
            the bibliographic record with the presentation fields that say
            how the site displays it. Empty when the site declares no
            citations.

        Raises
        ------
        sphinx.errors.ConfigError
            Raised if an entry names a CITATION.cff file that cannot be read,
            or if neither the entry nor its CITATION.cff file yields the DOI
            and title a citation needs.

        Notes
        -----
        Resolution reads any referenced CITATION.cff file, so it is deferred
        to first access and then cached: a configuration that is loaded but
        never displays a citation does no I/O.
        """
        return [
            self._resolve_citation(entry, index)
            for index, entry in enumerate(self.conf.project.citations)
        ]

    @property
    def self_citation(self) -> GuideCitation | None:
        """The citation whose DOI landing page this site is, or `None` if no
        entry claims it.
        """
        return next(
            (citation for citation in self.citations if citation.is_self),
            None,
        )

    def set_citations(self, html_context: MutableMapping[str, Any]) -> None:
        """Publish the resolved citations into Sphinx's ``html_context``.

        Parameters
        ----------
        html_context
            The Sphinx ``html_context`` mapping to populate.

        Notes
        -----
        Two keys are set, and only when the site declares at least one
        citation, so that a site without ``[[project.citations]]`` renders
        exactly as it did before:

        ``documenteer_citations``
            Every citation, in declaration order, as the mapping
            `~documenteer.citations.GuideCitation.to_html_context` composes.
        ``documenteer_self_citation``
            The entry from that list whose ``is_self`` is true, or `None`.

        This is the whole contract with the surfaces that display a citation
        — the ``<head>`` metadata, the ``citation-card`` directive, and the
        footer — which read the context and never recompose a citation.
        """
        contexts = [citation.to_html_context() for citation in self.citations]
        if not contexts:
            return
        html_context["documenteer_citations"] = contexts
        html_context["documenteer_self_citation"] = next(
            (context for context in contexts if context["is_self"]), None
        )
        jsonld = compose_landing_page_jsonld(
            contexts, site_url=self.base_url or None
        )
        if jsonld is not None:
            html_context["documenteer_citations_jsonld"] = jsonld

    def _resolve_citation(
        self, entry: CitationModel, index: int
    ) -> GuideCitation:
        """Compose one ``[[project.citations]]`` entry as a citation.

        A ``cff`` file supplies the bibliographic fields; a field set on the
        entry itself overrides the file's value.
        """
        source = self._read_citation_cff(entry, index) if entry.cff else None
        title = entry.title or (source.title if source else None)
        if title is None and entry.is_self:
            # The self citation is this site, so the site's own title is the
            # right title when nothing else supplies one.
            title = self.project
        if title is None:
            raise ConfigError(
                f"The {_describe_citation(entry, index)} declares no title. "
                "Set title, or set cff to a CITATION.cff file that declares "
                "one."
            )
        doi = entry.doi or (source.doi if source else None)
        if doi is None:
            raise ConfigError(
                f"The {_describe_citation(entry, index)} declares no DOI. "
                "Set doi, or set cff to a CITATION.cff file that declares "
                "one."
            )
        authors: tuple[CitationAuthor, ...]
        if entry.authors:
            authors = tuple(
                author.to_citation_author() for author in entry.authors
            )
        else:
            authors = source.authors if source else ()
        return GuideCitation(
            citation=Citation(
                title=title,
                type=entry.type or (source.type if source else None),
                doi=doi,
                authors=authors,
                publisher=entry.publisher
                or (source.publisher if source else None),
                date=entry.date or (source.date if source else None),
                url=source.url if source else None,
            ),
            label=entry.label,
            is_self=entry.is_self,
            in_footer=entry.shows_in_footer,
            note=entry.note,
        )

    def _read_citation_cff(self, entry: CitationModel, index: int) -> Citation:
        """Read the CITATION.cff file an entry names, relative to
        documenteer.toml.

        The path is resolved to an absolute one so that the error a missing
        or unreadable file raises names a path a reader can act on, rather
        than one still carrying the ``../`` the configuration wrote.
        """
        path = (self.root_dir / cast("str", entry.cff)).resolve()
        try:
            return read_citation_cff(path)
        except CitationCffError as e:
            raise ConfigError(
                f"The {_describe_citation(entry, index)} sets "
                f"cff = {entry.cff!r}, which could not be read as a "
                f"citation. {e}"
            ) from e


def _describe_citation(entry: CitationModel, index: int) -> str:
    """Identify a ``[[project.citations]]`` entry in an error message.

    The array has no names, so an entry is identified by its position, with
    its label added when it has one.
    """
    position = f"[[project.citations]] entry #{index + 1}"
    if entry.label:
        return f"{position} (label {entry.label!r})"
    return position
