"""Generation of a technote repository's CITATION.cff from technote.toml."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import date, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any, Self

import yaml

from documenteer.citations import (
    Citation,
    CitationAuthor,
    CitationType,
    OrganizationAuthor,
    PartialDate,
    PersonAuthor,
)
from documenteer.storage.authordb import normalize_orcid
from documenteer.storage.technotetoml import TechnoteTomlFile

__all__ = [
    "CFF_FILENAME",
    "CFF_HEADER",
    "CFF_MESSAGE",
    "CFF_VERSION",
    "CffStatus",
    "TechnoteCffError",
    "TechnoteCffService",
]

CFF_FILENAME = "CITATION.cff"
"""The filename GitHub looks for at a repository's root."""

CFF_VERSION = "1.2.0"
"""The version of the Citation File Format that is generated."""

CFF_HEADER = (
    "# Generated by documenteer technote sync-cff from technote.toml "
    "— do not edit\n"
)
"""The comment that opens every generated file.

The file is fully managed: `TechnoteCffService.sync` regenerates it from
scratch, so a hand-edit is lost on the next run. Saying so in the file itself
is the only place a reader is guaranteed to see it.
"""

CFF_MESSAGE = (
    "If you use this technote, please cite it using the metadata from "
    "this file."
)
"""The ``message`` field, which GitHub shows above the citation it renders."""

ORCID_RESOLVER = "https://orcid.org/"
"""The base URL an ORCID resolves at.

CFF requires an ORCID to be written as this URL, where ``technote.toml``
accepts several spellings.
"""

AUTHOR_TABLE_REMEDY = "Declare each author in a [[technote.authors]] table."
"""How to write an author, for a diagnostic to end with."""

AFFILIATION_TABLE_REMEDY = (
    "Declare each affiliation in a [[technote.authors.affiliations]] table "
    "with a name field."
)
"""How to write an affiliation, for a diagnostic to end with."""


class TechnoteCffError(ValueError):
    """Raised when technote.toml cannot be turned into a citation."""


class CffStatus(StrEnum):
    """The state of a CITATION.cff file relative to technote.toml."""

    absent = "absent"
    """No CITATION.cff exists.

    Adoption is opt-in per repository, so this is not a problem to report —
    it means the repository has not asked for a generated file.
    """

    current = "current"
    """CITATION.cff matches what technote.toml generates."""

    stale = "stale"
    """CITATION.cff exists but differs from what technote.toml generates."""


class _CffDumper(yaml.SafeDumper):
    """A YAML dumper that indents sequences under their parent key.

    PyYAML writes a sequence flush with the key that owns it, which is valid
    YAML but not how CFF files are conventionally written (nor how GitHub's
    own CITATION.cff template is laid out).
    """

    def increase_indent(
        self,
        flow: bool = False,  # noqa: FBT001, FBT002
        indentless: bool = False,  # noqa: FBT001, FBT002
    ) -> None:
        # PyYAML calls this positionally, so the signature is its to set;
        # `indentless` is discarded rather than forwarded, which is what
        # indents the sequence.
        super().increase_indent(flow=flow, indentless=False)


class TechnoteCffService:
    """Generates a technote repository's CITATION.cff from its technote.toml.

    ``technote.toml`` is the canonical source of a technote's metadata, and
    CITATION.cff is generated from it. Generation is deterministic and
    entirely local: the same technote.toml always yields byte-identical
    output, which is what lets `status` decide staleness by comparing content
    and lets ``--check`` — and the TN106 lint rule, which reuses this same
    comparison — run in CI without writing anything.

    Parameters
    ----------
    citation
        The technote's citation, composed from technote.toml.
    repository_url
        The technote's GitHub repository, if it declares one.
    warnings
        Notes about metadata that had to be guessed at, for the caller to
        report.
    """

    def __init__(
        self,
        citation: Citation,
        *,
        repository_url: str | None = None,
        warnings: Sequence[str] = (),
    ) -> None:
        self.citation = citation
        self.repository_url = repository_url
        self.warnings = tuple(warnings)

    @classmethod
    def from_technote_toml(cls, path: Path) -> Self:
        """Create the service by reading a technote.toml file.

        Parameters
        ----------
        path
            The path to the technote.toml file.

        Returns
        -------
        `TechnoteCffService`
            A service that generates CITATION.cff from that file.

        Raises
        ------
        ValueError
            Raised if the file is not valid TOML, or if it does not declare
            the metadata a citation needs.
        """
        return cls.from_metadata(TechnoteTomlFile.open(path).data)

    @classmethod
    def from_metadata(cls, data: Mapping[str, Any]) -> Self:
        """Create the service from parsed technote.toml data.

        Parameters
        ----------
        data
            The content of a technote.toml file as plain Python data.

        Returns
        -------
        `TechnoteCffService`
            A service that generates CITATION.cff from that metadata.

        Raises
        ------
        TechnoteCffError
            Raised if the metadata does not name the technote, or an author,
            at all, or if a table or array in it is written as some other
            TOML type.
        ValueError
            Raised if the technote declares something that is not a DOI.
        """
        technote = _table(
            data.get("technote"),
            subject="[technote]",
            remedy="Declare the technote's metadata in a [technote] table.",
        )
        warnings: list[str] = []

        technote_id = _text(technote.get("id"))
        title = _text(technote.get("title"))
        if title is None:
            if technote_id is None:
                raise TechnoteCffError(
                    "technote.toml declares neither a title nor an id, so "
                    f"there is nothing to name the technote in {CFF_FILENAME}."
                    " Add a title field to the [technote] table."
                )
            title = technote_id
            warnings.append(
                f"technote.toml declares no title, so {CFF_FILENAME} is "
                f"titled '{technote_id}'. Add a title field to the "
                "[technote] table to cite the technote by name."
            )

        organization = _table(
            technote.get("organization"),
            subject="[technote.organization]",
            remedy=(
                "Declare the publishing organization in a "
                "[technote.organization] table with a name field."
            ),
        )
        authors = _array(
            technote.get("authors"),
            subject="[[technote.authors]]",
            remedy=AUTHOR_TABLE_REMEDY,
        )
        citation = Citation(
            title=title,
            # A technote is a report, and saying so here is what makes the
            # citation read back from the generated file identical to this
            # one -- the round trip `tests/storage/citationcff_test.py` pins.
            type=CitationType.report,
            doi=_text(technote.get("doi")),
            authors=tuple(
                _citation_author(author, position)
                for position, author in enumerate(authors, start=1)
            ),
            publisher=_text(organization.get("name")),
            date=_released_date(technote),
            url=_text(technote.get("canonical_url")),
            number=technote_id,
        )
        return cls(
            citation,
            repository_url=_text(technote.get("github_url")),
            warnings=warnings,
        )

    def render(self) -> str:
        """Compose the CITATION.cff file.

        Returns
        -------
        str
            The complete file, header comment included.

        Notes
        -----
        A CFF file's top-level ``type`` may only be ``software`` or
        ``dataset``, neither of which a technote is. The top level is
        therefore a stub describing the repository, and the technote itself
        is the ``preferred-citation`` — a ``report`` reference, which is
        what GitHub renders and what carries the DOI, the series handle as
        ``number``, and the publishing institution.
        """
        document: dict[str, Any] = {
            "cff-version": CFF_VERSION,
            "message": CFF_MESSAGE,
            "title": self.citation.title,
            "type": "software",
            "authors": [
                _cff_author(author) for author in self.citation.authors
            ],
        }
        if self.repository_url:
            document["repository-code"] = self.repository_url
        if self.citation.url:
            document["url"] = self.citation.url
        document["preferred-citation"] = self._reference()

        body = yaml.dump(
            document,
            Dumper=_CffDumper,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            # Wide enough that a long title stays on one line rather than
            # being folded across several, which would be valid YAML but
            # awkward to read in a diff.
            width=4096,
        )
        return f"{CFF_HEADER}{body}"

    def status(self, path: Path) -> CffStatus:
        """Compare an existing CITATION.cff against technote.toml.

        Parameters
        ----------
        path
            The path the CITATION.cff file would live at.

        Returns
        -------
        `CffStatus`
            Whether the file is absent, current, or stale.
        """
        if not path.is_file():
            return CffStatus.absent
        current = path.read_text(encoding="utf-8") == self.render()
        return CffStatus.current if current else CffStatus.stale

    def sync(self, path: Path) -> CffStatus:
        """Write CITATION.cff unless it is already current.

        Parameters
        ----------
        path
            The path to write the CITATION.cff file to.

        Returns
        -------
        `CffStatus`
            The status the file had *before* the sync, so that a caller can
            report whether it wrote anything.
        """
        status = self.status(path)
        if status is not CffStatus.current:
            path.write_text(self.render(), encoding="utf-8")
        return status

    def _reference(self) -> dict[str, Any]:
        """Compose the ``preferred-citation`` reference."""
        citation = self.citation
        reference: dict[str, Any] = {
            "type": "report",
            "title": citation.title,
            "authors": [_cff_author(author) for author in citation.authors],
        }
        if citation.publisher:
            # A report's producing body is CFF's `institution`; a report has
            # no publisher distinct from it.
            reference["institution"] = {"name": citation.publisher}
        if citation.number:
            reference["number"] = citation.number
        if citation.doi:
            reference["doi"] = citation.doi
        location = citation.url or citation.doi_url
        if location:
            reference["url"] = location
        if citation.date is not None:
            # CFF's `date-released` is a full calendar date, so a citation
            # dated only to a year or a month — which a technote's never is,
            # but which a `Citation` can carry — is written as the `year` and
            # `month` a CFF reference states such a date with instead. Either
            # spelling reads back at the precision it was written at.
            released = citation.date.to_date()
            if released is not None:
                reference["date-released"] = released
            else:
                reference["year"] = citation.date.year
                if citation.date.month is not None:
                    reference["month"] = citation.date.month
        return reference


def _cff_author(author: CitationAuthor) -> dict[str, str]:
    """Express an author as a CFF ``Person`` or ``Entity``."""
    if isinstance(author, OrganizationAuthor):
        return {"name": author.name}
    entry = {"family-names": author.family_name}
    if author.given_name:
        entry["given-names"] = author.given_name
    if author.orcid:
        entry["orcid"] = f"{ORCID_RESOLVER}{normalize_orcid(author.orcid)}"
    if author.affiliation:
        entry["affiliation"] = author.affiliation
    return entry


def _citation_author(entry: Any, position: int) -> CitationAuthor:
    """Compose one ``[[technote.authors]]`` entry as a citation author.

    CFF records at most one affiliation per person, where technote.toml
    allows several, so the first affiliation that names itself is the one
    that is carried.

    ``position`` is the entry's 1-based place in the ``[[technote.authors]]``
    array. It is how a diagnostic points at the entry to fix: the entries are
    otherwise anonymous, and an entry malformed enough to report has no name
    to be named by.
    """
    where = f"[[technote.authors]] entry {position}"
    author = _table(entry, subject=where, remedy=AUTHOR_TABLE_REMEDY)
    name = _table(
        author.get("name"),
        subject=f"The name of {where}",
        remedy="Give it name.given and name.family fields.",
    )
    family_name = _text(name.get("family"))
    given_name = _text(name.get("given"))
    if family_name is None:
        if given_name is not None:
            # A mononym, or a corporate author written into the author list:
            # credit it as given rather than dropping it.
            return OrganizationAuthor(name=given_name)
        raise TechnoteCffError(
            f"{where} in technote.toml declares no name. Give every "
            "[[technote.authors]] entry a name.family value."
        )
    affiliations = _array(
        author.get("affiliations"),
        subject=f"The affiliations list of {where}",
        remedy=AFFILIATION_TABLE_REMEDY,
    )
    # Every affiliation is read before one is chosen, so that a malformed
    # entry is reported even when an earlier one already supplied the single
    # affiliation CFF carries.
    affiliation_names = [
        _text(
            _table(
                affiliation,
                subject=f"Affiliation {index} of {where}",
                remedy=AFFILIATION_TABLE_REMEDY,
            ).get("name")
        )
        for index, affiliation in enumerate(affiliations, start=1)
    ]
    return PersonAuthor(
        family_name=family_name,
        given_name=given_name,
        orcid=_text(author.get("orcid")),
        affiliation=next((n for n in affiliation_names if n), None),
    )


def _released_date(technote: Mapping[str, Any]) -> PartialDate | None:
    """Determine the technote's release date.

    ``date_updated`` is the date the technote was last published, and is
    therefore the date the citation is to; ``date_created`` stands in for a
    technote that has never been updated. Either is a full date, so a
    technote's citation is always dated to the day.
    """
    for field in ("date_updated", "date_created"):
        value = technote.get(field)
        if value is None:
            continue
        if isinstance(value, datetime):
            return PartialDate.from_date(value.date())
        if isinstance(value, date):
            return PartialDate.from_date(value)
        try:
            return PartialDate.from_date(
                datetime.fromisoformat(str(value)).date()
            )
        except ValueError as e:
            raise TechnoteCffError(
                f"technote.toml declares a {field} that is not a date: "
                f"{value}."
            ) from e
    return None


def _table(value: Any, *, subject: str, remedy: str) -> Mapping[str, Any]:
    """Read a TOML value that has to be a table, or report that it is not.

    ``sync-cff`` reads technote.toml through Documenteer's own reader rather
    than the technote package's pydantic models — deliberately, so that it
    runs without the technote extra — so nothing has validated the shape of
    what it reads. A hand-edited file can put a string where a table belongs,
    and the reader that then asks it for a field would raise an
    `AttributeError` naming neither the value nor where it came from. Saying
    both is what lets the person editing technote.toml find the entry to fix
    without bisecting the file.
    """
    if value is None:
        return {}
    if isinstance(value, Mapping):
        return value
    raise TechnoteCffError(
        f"{subject} in technote.toml is not a table: {value!r}. {remedy}"
    )


def _array(value: Any, *, subject: str, remedy: str) -> Sequence[Any]:
    """Read a TOML value that has to be an array, or report that it is not.

    A string is a sequence in Python but not an array in TOML, so it is
    reported rather than iterated character by character.
    """
    if value is None:
        return ()
    if isinstance(value, Sequence) and not isinstance(value, str | bytes):
        return value
    raise TechnoteCffError(
        f"{subject} in technote.toml is not an array: {value!r}. {remedy}"
    )


def _text(value: Any) -> str | None:
    """Reduce a TOML value to non-empty text, or `None`."""
    if value is None:
        return None
    text = " ".join(str(value).split())
    return text or None
